apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: time-since-function
  namespace: nuclio
spec:
  description: Returns the time that has passed since a specific date
  runtime: "python:3.6"
  handler: "time-since:handler"
  minReplicas: 1
  maxReplicas: 1

  build:
    commands:
    - "pip install python-dateutil"
